### ISSUE TITLE
HA Thersmostat current temperature

### ISSUE THREAD

**Issue by TimoAinali** [superrob/genvexnabto#5]
First, thank you for the great integration. I found it by accident and I have been testing it with Nilan 400 Polar Top for few days and can confirm that it works flawlesly.
Integration creates a climate entity, it seems to use "Extract air" temperature as current temperatury instead of "Room temperature" ?  
Another question, what is the meaning of "Temperature" under configuration, seems to go from 0 -365 ? There is also "Temperature target" under controls that goes from 0 to 30 and is the same as in Nilan display

Thanks,

Timo

**Comment by superrob** [comment]
This isn't the issues for the integration.
That is in the GenvexConnect repo :)

As for the temperature issue, please see the existing issue: https://github.com/superrob/genvexconnect/issues/13
